# Generated by Django 2.2.1 on 2019-06-17 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cricket', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matches',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
