# Generated by Django 2.2.1 on 2019-06-17 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cricket', '0002_auto_20190617_1144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matches',
            name='date',
            field=models.DateField(),
        ),
    ]
