# Generated by Django 2.2.1 on 2019-06-17 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cricket', '0004_auto_20190617_1216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matches',
            name='umpire3',
            field=models.CharField(default=None, max_length=164, null=True),
        ),
    ]
