# Generated by Django 2.2.1 on 2019-06-17 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cricket', '0005_auto_20190617_1217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matches',
            name='umpire3',
            field=models.CharField(blank=True, default=None, max_length=164, null=True),
        ),
    ]
