# Generated by Django 2.2.1 on 2019-06-17 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cricket', '0006_auto_20190617_1227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matches',
            name='city',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='matches',
            name='player_of_the_match',
            field=models.CharField(blank=True, max_length=164, null=True),
        ),
        migrations.AlterField(
            model_name='matches',
            name='result',
            field=models.CharField(blank=True, max_length=164, null=True),
        ),
        migrations.AlterField(
            model_name='matches',
            name='team1',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='matches',
            name='team2',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='matches',
            name='toss_decision',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='matches',
            name='toss_winner',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='matches',
            name='umpire1',
            field=models.CharField(blank=True, max_length=164, null=True),
        ),
        migrations.AlterField(
            model_name='matches',
            name='umpire2',
            field=models.CharField(blank=True, max_length=164, null=True),
        ),
        migrations.AlterField(
            model_name='matches',
            name='umpire3',
            field=models.CharField(blank=True, max_length=164, null=True),
        ),
        migrations.AlterField(
            model_name='matches',
            name='venue',
            field=models.CharField(blank=True, max_length=164, null=True),
        ),
        migrations.AlterField(
            model_name='matches',
            name='winner',
            field=models.CharField(blank=True, max_length=164, null=True),
        ),
    ]
